# Generated by Django 4.2 on 2023-09-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpendPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=100)),
                ("explaination", models.TextField()),
                ("generic_demand", models.FloatField()),
                ("isIncome", models.BooleanField()),
            ],
            options={
                "verbose_name": "SpendPoint",
                "verbose_name_plural": "SpendPoints",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_point", models.IntegerField()),
                ("base_point_predict", models.IntegerField(blank=True, null=True)),
                (
                    "base_point_penalty_if_fail",
                    models.IntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("note_prediction", models.TextField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.spendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "managed": True,
            },
        ),
    ]
