# Generated by Django 4.2 on 2023-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOOKED", "BOOKED"),
                    ("DOING", "DOING"),
                    ("DONE", "DONE"),
                    ("REVIEW", "REVIEW"),
                ],
                default="BOOKED",
                max_length=30,
                null=True,
            ),
        ),
    ]
